version: "2"

services:
    elasticsearch:
        container_name: elasticsearch_container
        #image: elasticsearch:6.6.2
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
        networks:
          - es-net
        ports: 
          - 9200:9200
          - 9300:9300
        environment:
          - discovery.type=single-node
          - xpack.monitoring.enabled=true
    #kibana:
        #container_name: kibana_container
        #image: docker.elastic.co/kibana/kibana:7.11.0
        #depends_on: 
          #- elasticsearch
        #networks:
          #- es-net
        #ports: 
          #- 5601:5601
        #environment:
          #- ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    redis:
        container_name: "redis"
        image: redis
        ports:
          - 6379:6379
networks:
    es-net:
        driver: bridge
