spring:
    application:
        name: product-catalog
        
    cloud:
        config:
            uri: http://localhost:8888
            import-check:
                enabled: false
#spring.cloud.config.enabled=true
#spring.cloud.config.import-check.enabled=false
